// RenderCore/IblShCoeffs.h
//
// AUTO-GENERATED by tools/ibl/project_sh.py. Do not edit by hand.
// Tool: V-IBL-STATIC-1 v1
// Source HDRI: data/hdr/DaySkyHDRI063B_4K.exr
// Source sha256: b4bd5cee3abfa121742d71fdf5c8320b7ca2867a64127d3445f681f4f4026a7a
//
// V-IBL-STATIC-1: spherical-harmonic ambient coefficients, SH-L2
// (9 bands), projected analytically per Ramamoorthi-Hanrahan 2001 from
// the equirectangular HDRI sample above. Values are RAW projection
// integrals C_lm = integral(L * Y_lm dw); the shader evaluator
// shaders/static_prop.vert::evalShL2 absorbs the per-band diffuse
// cosine-lobe kernel (pi, 2pi/3, pi/4) into its Ramamoorthi-Hanrahan
// c1..c5 constants, yielding diffuse IRRADIANCE directly. Do NOT
// premultiply the kernel here and do NOT apply an additional /pi
// in the consumer -- c1..c5 ARE the pre-convolved kernel.
//
// Coefficient order (must match projector + shader evaluator):
//   [0]=L00, [1]=L1-1, [2]=L10, [3]=L11,
//   [4]=L2-2, [5]=L2-1, [6]=L20, [7]=L21, [8]=L22
//
// Axis convention: Y-up world. Projection uses Y-pole basis (L20 binds
// to (3*y^2 - 1), L22 to (x^2 - z^2)), matching static_prop.vert worldNormal
// which is Stuff-space Y-up (model normal * mat3(modelMatrix); position-only
// Stuff->MC2 axis swap leaves the normal in Stuff Y-up). The HDRI is decoded
// here with the same UV->direction mapping as hdri_skybox.frag:30-33.
//
// Firewall: header-only constexpr. No GL, no game-side includes.

#pragma once

namespace RenderCore {

// 9 SH-L2 coefficients * 3 channels (R, G, B).
constexpr float kIblShCoeffs[9][3] = {
    { +1.713250528e+00f, +1.773145394e+00f, +1.652499519e+00f }, // L00 
    { +5.869951003e-01f, +5.782034038e-01f, +5.179309118e-01f }, // L1-1
    { +1.179062044e-02f, +1.345766309e-03f, -8.740967483e-03f }, // L10 
    { +1.966354845e+00f, +1.856721003e+00f, +1.505876116e+00f }, // L11 
    { +1.334658751e+00f, +1.287703421e+00f, +1.077505997e+00f }, // L2-2
    { +1.688171049e-02f, +1.641851255e-02f, +1.176750778e-02f }, // L2-1
    { -1.016652552e+00f, -9.684202893e-01f, -7.816944278e-01f }, // L20 
    { +5.064675817e-02f, +4.545421310e-02f, +3.281146747e-02f }, // L21 
    { +1.962057200e+00f, +1.850144657e+00f, +1.499676879e+00f }, // L22 
};

} // namespace RenderCore
