#!/usr/bin/env python3
"""check-env-vars-documented.py -- env-var documentation drift reporter.

Pure reporter over COMMITTED files (no regeneration -- that is
check-flag-registry-drift.sh's job):
  - docs/flags.auto.yaml   (generated by scripts/flag-registry-auto-gen.py)
  - docs/tier1_env_vars.md (hand-maintained docs)

Categories:
  1. MISSES  -- registered flags (registered: yes) NOT documented in
     tier1_env_vars.md (documented_in_tier1_env_vars: no). Primary list.
  2. UNREGISTERED SWEEP (informational) -- getenv-sweep flags with
     registered: no; count + top offender dirs by first referenced_at.
  3. STALE DOCS -- MC2_* names in tier1_env_vars.md that no longer exist
     in flags.auto.yaml.

Advisory: exit 0 always, unless --strict AND category 1 non-empty.
"""

import argparse
import collections
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
YAML_PATH = os.path.join(REPO_ROOT, "docs", "flags.auto.yaml")
DOCS_PATH = os.path.join(REPO_ROOT, "docs", "tier1_env_vars.md")


def parse_flags(path):
    """Minimal parser for the machine-generated flags.auto.yaml.

    No pyyaml dependency: the generator emits a rigid line format
    ('  - name: X' then '    key: value' / '      - listitem').
    """
    flags = []
    cur = None
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^  - name: (\S+)\s*$", line)
            if m:
                cur = {"name": m.group(1), "registered": "no",
                       "documented_in_tier1_env_vars": "no",
                       "referenced_at": []}
                flags.append(cur)
                continue
            if cur is None:
                continue
            m = re.match(r"^    (\w+): (.*?)\s*$", line)
            if m:
                cur[m.group(1)] = m.group(2).strip('"')
                continue
            m = re.match(r"^      - (\S+)\s*$", line)
            if m:
                cur["referenced_at"].append(m.group(1))
    return flags


def doc_flag_names(path):
    with open(path, "r", encoding="utf-8") as f:
        return set(re.findall(r"MC2_[A-Z0-9_]+", f.read()))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 if any registered flag is undocumented")
    args = ap.parse_args()

    for p in (YAML_PATH, DOCS_PATH):
        if not os.path.isfile(p):
            print("ERROR: missing %s" % p, file=sys.stderr)
            return 1 if args.strict else 0

    flags = parse_flags(YAML_PATH)
    yaml_names = {f["name"] for f in flags}
    doc_names = doc_flag_names(DOCS_PATH)

    # Category 1: registered but undocumented.
    misses = sorted(f["name"] for f in flags
                    if f.get("registered") == "yes"
                    and f.get("documented_in_tier1_env_vars") != "yes")

    # Category 2: unregistered sweep flags (informational).
    unreg = [f for f in flags if f.get("registered") != "yes"]
    dir_counts = collections.Counter()
    for f in unreg:
        refs = f["referenced_at"]
        if refs:
            # strip :line, take top-level dir of first reference
            dir_counts[refs[0].split(":")[0].split("/")[0]] += 1

    # Category 3: documented flags gone from the yaml (stale docs).
    stale = sorted(doc_names - yaml_names)

    print("== env-var documentation drift (advisory) ==")
    print("yaml flags: %d  registered: %d  documented in tier1_env_vars.md: %d"
          % (len(flags), len(flags) - len(unreg), len(doc_names)))
    print()
    print("1. REGISTERED BUT UNDOCUMENTED in docs/tier1_env_vars.md: %d"
          % len(misses))
    for n in misses:
        print("   MISS %s" % n)
    print()
    print("2. UNREGISTERED getenv-sweep flags (informational): %d" % len(unreg))
    for d, c in sorted(dir_counts.items(), key=lambda kv: (-kv[1], kv[0]))[:5]:
        print("   %4d  %s/" % (c, d))
    print()
    print("3. STALE DOCS (in tier1_env_vars.md, gone from yaml): %d" % len(stale))
    for n in stale:
        print("   STALE %s" % n)
    print()
    if misses:
        print("ADVISORY: %d registered flag(s) undocumented -- add to "
              "docs/tier1_env_vars.md" % len(misses))
    else:
        print("OK: all registered flags documented")

    return 1 if (args.strict and misses) else 0


if __name__ == "__main__":
    sys.exit(main())
