# cmake/GenerateBuildFingerprint.cmake
#
# Script mode (cmake -P). Generates build_fingerprint.h with the git identity
# of the source worktree so the exe carries its own deploy fingerprint
# (printed at startup as "[BUILD_FINGERPRINT v1] ..." and asserted by
# scripts/run_smoke.py). Stronger sibling of scripts/check-deploy-coherence.py:
# survives exe copies between deploy dirs.
#
# Inputs (via -D):
#   OUT     — absolute path of the header to write
#   SRC_DIR — source worktree root (git repo / worktree)
#
# Runs on EVERY build (add_custom_target in CMakeLists.txt), but only rewrites
# the header when sha/dirty/branch/src changed — the build-time line is
# excluded from the comparison, so a no-op rebuild does not touch the header
# and does not force recompiles. "built=" therefore reflects the time of the
# last fingerprint-content change, not the last incremental link.

if(NOT OUT OR NOT SRC_DIR)
    message(FATAL_ERROR "GenerateBuildFingerprint.cmake requires -DOUT=... -DSRC_DIR=...")
endif()

find_program(MC2_GIT_EXE git)

set(_sha "unknown")
set(_dirty 0)
set(_branch "unknown")

if(MC2_GIT_EXE)
    execute_process(COMMAND "${MC2_GIT_EXE}" -C "${SRC_DIR}" rev-parse HEAD
                    OUTPUT_VARIABLE _sha_full OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE _rc_sha)
    if(_rc_sha EQUAL 0 AND _sha_full)
        string(SUBSTRING "${_sha_full}" 0 12 _sha)
    endif()
    # Dirty = uncommitted changes to TRACKED files (untracked ignored).
    execute_process(COMMAND "${MC2_GIT_EXE}" -C "${SRC_DIR}" status --porcelain -uno
                    OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE _rc_st)
    if(_rc_st EQUAL 0 AND NOT _status STREQUAL "")
        set(_dirty 1)
    endif()
    execute_process(COMMAND "${MC2_GIT_EXE}" -C "${SRC_DIR}" rev-parse --abbrev-ref HEAD
                    OUTPUT_VARIABLE _branch_out OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE _rc_br)
    if(_rc_br EQUAL 0 AND _branch_out)
        set(_branch "${_branch_out}")
    endif()
endif()

string(TIMESTAMP _built "%Y-%m-%dT%H:%M:%S")

set(_content "// Generated by cmake/GenerateBuildFingerprint.cmake — do not edit.
#ifndef MC2_BUILD_FINGERPRINT_H
#define MC2_BUILD_FINGERPRINT_H
#define MC2_BUILD_GIT_SHA \"${_sha}\"
#define MC2_BUILD_GIT_DIRTY ${_dirty}
#define MC2_BUILD_GIT_BRANCH \"${_branch}\"
#define MC2_BUILD_TIME_ISO \"${_built}\"
#define MC2_BUILD_SRC_WORKTREE \"${SRC_DIR}\"
#endif
")

# Only-if-changed, ignoring the MC2_BUILD_TIME_ISO line on both sides.
set(_write 1)
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
    string(REGEX REPLACE "#define MC2_BUILD_TIME_ISO \"[^\"]*\"" "" _old_cmp "${_old}")
    string(REGEX REPLACE "#define MC2_BUILD_TIME_ISO \"[^\"]*\"" "" _new_cmp "${_content}")
    if(_old_cmp STREQUAL _new_cmp)
        set(_write 0)
    endif()
endif()

if(_write)
    file(WRITE "${OUT}" "${_content}")
    message(STATUS "build_fingerprint.h: sha=${_sha} dirty=${_dirty} branch=${_branch}")
endif()
